#!/usr/bin/python3.0

import sys
import random
import time
Usage = SystemExit("Usage: ./tools/fuzz [seed]")
if len(sys.argv) == 2:
  try:
    seed = int(sys.argv[1])
  except:
    raise Usage
elif len(sys.argv) != 1:
  raise Usage
else:
  seed = int(time.time()*1000)
print("Seed is", seed, file=sys.stderr)
r = random.Random(seed)

for _ in range(1024):
	print(r.choice(' abcdefg\'ijklmnoprstuvxyz.,'), end='')
