#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
This is a wrapper around the zirsam module.
"""


import zirsam.dendrography

try:
  for val in zirsam.dendrography.Stream():
    print(val)
except KeyboardInterrupt:
  pass
